c     This subroutine reads file movie.xyz generated by Ramin's code
c     and determines obstacle coordinates
c   
c     Nobs = # obstacles from program
c     Nparts = # obstacles in movie.xyz
c     xobs, yobs = obstacle center xy coords
c     zobs = z coords in file, garbage values
c     not computed in 2D magnetic bead simulation
c
c     March 23 2007
c
      subroutine readobst(Nobs, xobs, yobs)
      
      implicit none
      integer Nobs, Nparts, iobs
      real*8 xobs(Nobs), yobs(Nobs), zobs(Nobs)
      logical isobscoords
      character*32 header

c     iobs = counter over obstacle indices
c     isobscoords indicates whether or not file containing obst coords exists
c     header = unnecessary character strings in movie.xyz

c     check if obstacle coords file exists, if not, stop program
      inquire(file = 'movie.xyz', exist = isobscoords)
      if(.NOT.isobscoords) then
        write(*, *) 'generate obstacle coordinates and restart; bye'
        stop
      endif

c     check if Nparts and Nobs are equal, if not, stop program
      open(unit = 1, file = 'movie.xyz', status = 'OLD')      
3     read(1, *) header
      if(header.eq.'#') goto 3
      backspace(unit = 1)
      read(1, *) Nparts
      if(Nparts.ne.Nobs) then
        write(*, *) 'unequal #obstacles in file and in program'
        write(*, *) 'bye'
        stop
      endif
      read(1, *)
c     now read and save obstacle coordinates
      do 20 iobs = 1, Nobs
         read(1,*) header, xobs(iobs), yobs(iobs), zobs(iobs)
 20   continue
      close(unit = 1, status = 'KEEP')

      return
      end
