c     This subroutine reads file movie.xyz generated by Ramin's code
c     and determines obstacle coordinates
c     Minor variant of readobst.f -- movie.xyz is now opened in 
c     the program instead of in this subroutine
c   
c     nobsfile = unit# of movie.xyz file
c     Nobs = # obstacles from program
c     Nparts = # obstacles in movie.xyz
c     xobs, yobs = obstacle center xy coords
c     zobs = z coords in file, garbage values
c     not computed in 2D magnetic bead simulation
c
c     Apr 10 2007
c
      subroutine readobstq(nobsfile, Nobs, xobs, yobs)
      
      implicit none
      integer nobsfile, Nobs, Nparts, iobs
      real*8 xobs(Nobs), yobs(Nobs), zobs
      character*32 header

c     iobs = counter over obstacle indices
c     header = unnecessary character strings in movie.xyz

c     check if Nparts and Nobs are equal, if not, stop program 
3     read(nobsfile, *) header
      if(header.eq.'#') goto 3
      backspace(unit = nobsfile)
      read(nobsfile, *) Nparts
      if(Nparts.ne.Nobs) then
        write(*, *) 'unequal #obstacles in file and in program'
        write(*, *) 'bye'
        stop
      endif
      read(nobsfile, *)
c     now read and save obstacle coordinates
      do 20 iobs = 1, Nobs
         read(nobsfile, *) header, xobs(iobs), yobs(iobs), zobs
 20   continue

      return
      end
